"""
Django settings for saferoute_project project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load a local .env file if python-dotenv is installed and a .env exists.
# Nothing breaks if either is missing — this is purely a convenience so
# developers don't have to `export` variables by hand for local runs.
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / ".env")
except ImportError:
    pass


def _env_bool(name, default):
    val = os.environ.get(name)
    if val is None:
        return default
    return val.strip().lower() in ("1", "true", "yes", "on")


# SECURITY WARNING: keep the secret key used in production secret!
# Reads from DJANGO_SECRET_KEY. The literal fallback below is ONLY for
# convenience running the project locally out of the box — it must never
# be relied on outside local dev; set DJANGO_SECRET_KEY everywhere else.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-@c)0x+)+a3pt_#v*z+72!k0)$jg+arkfk^k+5!7y5sen0+k_sm",
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to True to preserve the previous local-dev behavior; set
# DJANGO_DEBUG=false in any real deployment.
DEBUG = _env_bool("DJANGO_DEBUG", True)

# Comma-separated list, e.g. DJANGO_ALLOWED_HOSTS=api.example.com,example.com
ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()
]
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'saferoute_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'saferoute_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# --- SafeRoute additions ---

AUTH_USER_MODEL = "core.SafeRouteUser"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    # BUG FIX: DRF's default exception handler only turns APIException
    # subclasses into a Response — any other unhandled exception (KeyError,
    # TypeError, a third-party library error, etc.) falls straight through
    # to Django's bare error page instead. That response isn't guaranteed
    # to carry the CORS headers corsheaders adds to normal DRF Responses,
    # so the browser reports "blocked by CORS policy" instead of the real
    # 500 (exactly what happened on /api/routes/plan-multi/). This handler
    # is a last-resort net across *every* API view: it logs the real
    # traceback and always returns a normal, CORS-safe JSON 500.
    "EXCEPTION_HANDLER": "core.exceptions.custom_exception_handler",
}

# BUG FIX: simplejwt defaults ACCESS_TOKEN_LIFETIME to just 5 minutes when
# left unconfigured. With no refresh flow wired up on the frontend, every
# user was getting silently logged out (401s on /auth/me/, /incidents/,
# /routes/history/, etc.) a few minutes into a session. Give access tokens
# a realistic lifetime for a browser session and refresh tokens a week.
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=12),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
}

# Allow all origins and Vercel deployment subdomains (*.vercel.app).
# CORS_ALLOW_ALL_ORIGINS already covers every origin including the
# production frontend below; CORS_ALLOWED_ORIGINS/REGEXES are kept as an
# explicit, human-readable record of who's expected to call this API and
# as a fallback if CORS_ALLOW_ALL_ORIGINS is ever turned off.
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    "https://saferoute-india.vercel.app",
]
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.vercel\.app$",
]
# Make sure CORS headers are attached even to error responses (400/500),
# not just 2xx ones — this is the default, but explicit here since that's
# precisely the case that was breaking above.
CORS_ALLOW_CREDENTIALS = False



OSRM_BASE_URL = os.environ.get("OSRM_BASE_URL", "https://router.project-osrm.org")

# OpenStreetMap / Overpass — see core/services/osm.py
OVERPASS_URL = os.environ.get("OVERPASS_URL", "https://overpass-api.de/api/interpreter")
OSM_REQUEST_TIMEOUT_SECONDS = int(os.environ.get("OSM_REQUEST_TIMEOUT_SECONDS", "12"))
OSM_CACHE_TTL_SECONDS = int(os.environ.get("OSM_CACHE_TTL_SECONDS", str(24 * 60 * 60)))

# Real incident data source (see core/services/incident_ingest.py). Can
# point at a local CSV/JSON path or a remote http(s) URL (e.g. a city
# open-data portal export). Left unset, ingestion just uses the
# hand-curated core/data.csv baseline that ships with the repo.
INCIDENT_DATA_SOURCE = os.environ.get("INCIDENT_DATA_SOURCE", "")

# File-based cache so Overpass responses survive process restarts
# (a plain in-memory cache would refetch on every `runserver` reload).
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": str(BASE_DIR / ".cache" / "osm"),
        "TIMEOUT": OSM_CACHE_TTL_SECONDS,
    }
}

# Route planning previously debugged itself with bare print() calls
# (OSRM route counts, dedup results, final route summaries), which can't
# be turned off/on or routed anywhere except stdout. This wires the same
# messages through logging instead: DEBUG-level detail shows up locally
# (DEBUG=True) but is silent in any deployment unless DJANGO_LOG_LEVEL is
# set explicitly, so production logs aren't flooded with per-request
# route-scoring detail by default.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "loggers": {
        "core": {
            "handlers": ["console"],
            "level": os.environ.get("DJANGO_LOG_LEVEL", "DEBUG" if DEBUG else "WARNING"),
        },
    },
}
