# Generated by Django 6.0.7 on 2026-07-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_saferouteuser_emergency_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='source',
            field=models.CharField(choices=[('System', 'System'), ('Community', 'Community'), ('Historical', 'Historical')], default='Community', max_length=10),
        ),
    ]
