# Generated by Django 6.1 on 2026-08-10 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_incident_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saferouteuser',
            name='emergency_contacts',
        ),
    ]
